### PR TITLE
chore: pin edk to v0.1.0

### PR DESCRIPTION
**Pull request by pnadolny13**
Related to https://github.com/meltano/hub/issues/1115

### CODE REVIEW

**Review by WillDaSilva — APPROVED** [review]

**Comment by pnadolny13** [comment]
@edgarrmondragon @WillDaSilva any idea why this test is failing? It says models doesnt exist but looks like it does https://github.com/meltano/edk/blob/main/meltano/edk/models.py.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon @WillDaSilva any idea why this test is failing? It says models doesnt exist but looks like it does [meltano/edk@`main`/meltano/edk/models.py](https://github.com/meltano/edk/blob/main/meltano/edk/models.py?rgh-link-date=2023-01-26T19%3A59%3A53Z).

@pnadolny13 I'll update mypy 🤞

**Review by edgarrmondragon — APPROVED** [review]
@pnadolny13 Had to fix the import and EDK usage. This is g2g now, I think but I'd test it before 😅

**Comment by pnadolny13** [comment]
@edgarrmondragon I actually cant get this working 🤔 although I'm not sure its related to this PR specifically, looking into it more

**Comment by edgarrmondragon** [comment]
@pnadolny13 Any luck figuring out those failures?

**Comment by pnadolny13** [comment]
@edgarrmondragon I havent had time to try again but when I tried last week I was getting failures going through the hub getting started steps when pointing to main so I didnt have a base case to tests this branch against.

**Comment by pnadolny13** [comment]
@edgarrmondragon I confirmed this is good! I also found some bugs related to it and fixed them in https://github.com/meltano/hub/pull/1169.

**Pull request merged**
